general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

# 1. Atenuar el brillo suavemente tras 3 minutos de inactividad
listener {
    timeout = 180
    on-timeout = ~/.config/hypr/scripts/fade_brightness.sh
    on-resume = brightnessctl -r
}

# 2. Bloquear con Hyprlock tras 5 minutos
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}