# ==============================================================================
# TYPOGRAPHY & FONTS
# ==============================================================================
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# Desactivar ligaduras al posar el cursor encima
disable_ligatures cursor

# ==============================================================================
# WINDOW & PADDING
# ==============================================================================
# Transparencia del fondo (0.85 da un toque semi-translúcido genial)
background_opacity 0.85

# Acolchado interno (Padding) para que el texto no pegue en las orillas
window_padding_width 12

# Ocultar barra de título nativa (gestionado por Hyprland)
hide_window_decorations yes
confirm_os_window_close 0

# Bell silencioso (sin pitido del sistema)
enable_audio_bell no

# ==============================================================================
# CURSOR
# ==============================================================================
cursor_shape beam
cursor_blink_interval 0.5

# ==============================================================================
# COLOR SCHEME (Tokyo Night)
# ==============================================================================
foreground              #c0caf5
background              #1a1b26
selection_foreground    #c0caf5
selection_background    #2e3c64

# Cursor
cursor                  #c0caf5
cursor_text_color       #1a1b26

# URLs
url_color               #73daca

# Bordes de pestañas/ventanas
active_border_color     #7aa2f7
inactive_border_color   #292e42
bell_border_color       #e0af68

# Colores ANSI Estándar (16 Colores)
# Negro
color0 #15161e
color8 #414868

# Rojo
color1 #f7768e
color9 #f7768e

# Verde
color2  #9ece6a
color10 #9ece6a

# Amarillo
color3  #e0af68
color11 #e0af68

# Azul
color4  #7aa2f7
color12 #7aa2f7

# Magenta
color5  #bb9af7
color13 #bb9af7

# Cian
color6  #7dcfff
color14 #7dcfff

# Blanco
color7  #a9b1d6
color15 #c0caf5